-- MySQL Script generated by MySQL Workbench
-- Wed Jun  1 08:40:01 2022
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema projet4
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema projet4
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `projet4` DEFAULT CHARACTER SET utf8 ;
USE `projet4` ;

-- -----------------------------------------------------
-- Table `projet4`.`users`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `projet4`.`users` ;

CREATE TABLE IF NOT EXISTS `projet4`.`users` (
  `usr_id` INT NOT NULL AUTO_INCREMENT,
  `usr_email` VARCHAR(128) NOT NULL,
  `usr_pwd` VARCHAR(64) NOT NULL,
  `usr_pseudo` VARCHAR(64) NOT NULL,
  `usr_status` VARCHAR(3) NOT NULL,
  `usr_role` VARCHAR(3) NOT NULL,
  PRIMARY KEY (`usr_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `projet4`.`billets`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `projet4`.`billets` ;

CREATE TABLE IF NOT EXISTS `projet4`.`billets` (
  `bil_id` INT NOT NULL AUTO_INCREMENT,
  `bil_text` TEXT NOT NULL,
  `bil_pub_date` TIMESTAMP NOT NULL,
  `users_usr_id` INT NOT NULL,
  PRIMARY KEY (`bil_id`, `users_usr_id`),
  CONSTRAINT `fk_billets_users`
    FOREIGN KEY (`users_usr_id`)
    REFERENCES `projet4`.`users` (`usr_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_billets_users_idx` ON `projet4`.`billets` (`users_usr_id` ASC);


-- -----------------------------------------------------
-- Table `projet4`.`comments`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `projet4`.`comments` ;

CREATE TABLE IF NOT EXISTS `projet4`.`comments` (
  `cmt_id` INT NOT NULL AUTO_INCREMENT,
  `cmt_text` TEXT NOT NULL,
  `usr_id` INT NOT NULL,
  `cmt_like` TINYINT NOT NULL,
  `cmt_dislike` TINYINT NOT NULL,
  `users_usr_id` INT NOT NULL,
  `bil_id` INT NOT NULL,
  `billets_bil_id` INT NOT NULL,
  PRIMARY KEY (`cmt_id`, `users_usr_id`, `billets_bil_id`),
  CONSTRAINT `fk_comments_users1`
    FOREIGN KEY (`users_usr_id`)
    REFERENCES `projet4`.`users` (`usr_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_comments_billets1`
    FOREIGN KEY (`billets_bil_id`)
    REFERENCES `projet4`.`billets` (`bil_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_comments_users1_idx` ON `projet4`.`comments` (`users_usr_id` ASC);

CREATE INDEX `fk_comments_billets1_idx` ON `projet4`.`comments` (`billets_bil_id` ASC);


-- -----------------------------------------------------
-- Table `projet4`.`logs`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `projet4`.`logs` ;

CREATE TABLE IF NOT EXISTS `projet4`.`logs` (
  `log_id` INT NOT NULL,
  `log_date` DATETIME NOT NULL,
  `log_message` VARCHAR(128) NOT NULL,
  `log_type` VARCHAR(3) NOT NULL DEFAULT 'check (log_type in ( \'USR\', \'PRG\'))',
  PRIMARY KEY (`log_id`))
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
